### ISSUE TITLE
This repo exposes paid plugin to public!

### ISSUE THREAD

**Issue by KyryloKuzyk** [NamgarM/Boom-AR#31]
Hi,

This is Kirill, creator of the plugin:
https://assetstore.unity.com/packages/tools/utilities/ar-foundation-editor-remote-168773

Please make your repository private because it exposes the plugin's source code to the public. To be exact, the 'Plugins/ARFoundationRemoteInstaller/' folder.

An alternative to making your repo private is to remove the plugin from your git repo and clean the commit history:
https://stackoverflow.com/questions/13716658/how-to-delete-all-commit-history-in-github

Thanks for your understanding.

**Comment by NamgarM** [comment]
Hello,

Thank you for notifying, I cleaned the history.

Sent from ProtonMail mobile

-------- Original Message --------
